# Generated by Django 4.2.16 on 2024-09-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_author_id_alter_post_id_alter_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_name',
            new_name='image_name',
        ),
    ]
